import { nanoid } from "nanoid"
export const bookData = [
        {
            id: nanoid(),
            img: 'https://i.pinimg.com/736x/9f/6f/81/9f6f81ec648dcbdf6691f2f590bd2b5b.jpg',
            title: 'The Great Gatsby',
            author: 'F. Scott Fitzgerald',
            type: 'Fiction',
            description: 'A story of the young and mysterious millionaire Jay Gatsby and his quixotic passion for the beautiful Daisy Buchanan.',
            rating: '4.3',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi6jB49CUWKvbNKfdu9gwYJXoovNzs0WdSRg&s',
            title: 'To Kill a Mockingbird',
            author: 'Harper Lee',
            type: 'Fiction',
            description: 'A young girl grows up in a racially charged society and learns from her father, a moral lawyer, about justice and empathy.',
            rating: '4.5',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLhGLBsK1JN9no8HAEaihCRtKSP0MznYdcSQ&s',
            title: 'Dune',
            author: 'Frank Herbert',
            type: 'Sci-Fi',
            description: 'An epic science fiction tale of politics, religion, and power set on the desert planet Arrakis.',
            rating: '4.6',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTncQwLgvNirI9xcR07HP11qY74hdJhvZthew&s',
            title: 'Sapiens: A Brief History of Humankind',
            author: 'Yuval Noah Harari',
            type: 'Non-Fiction',
            description: 'A groundbreaking look at the history and evolution of humans, exploring how Homo sapiens came to dominate the world.',
            rating: '4.7',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvmXSPue6EaswVgB-LlMwtlKI66Uv8NFx-ew&s',
            title: 'The Catcher in the Rye',
            author: 'J.D. Salinger',
            type: 'Fiction',
            description: 'A teenage boy recounts his experiences in New York City, offering insight into alienation and teenage angst.',
            rating: '4.4',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9EKN6r-jZgRkXQ7wHzA2Ue6KrVXOW41UKJg&s',
            title: 'Brave New World',
            author: 'Aldous Huxley',
            type: 'Sci-Fi',
            description: 'A dystopian society engineered for stability is revealed as dehumanizing and controlling in this classic novel.',
            rating: '4.5',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf21yE0QhGO8nNOLbesrXdyDsR1aMq8fPXCw&s ',
            title: 'Educated',
            author: 'Tara Westover',
            type: 'Non-Fiction',
            description: 'A memoir of a woman who grows up in a strict and abusive household in rural Idaho and goes on to earn a PhD from Cambridge University.',
            rating: '4.7',
        },
        {
            id: nanoid(),
            img: ' https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIyF65wMcHix5kb_XrYhxZZl3sbGIby7OQgg&s',
            title: 'The Alchemist',
            author: 'Paulo Coelho',
            type: 'Fiction',
            description: 'An allegorical tale of a young shepherd on a journey to fulfill his personal legend and seek his treasure.',
            rating: '4.4',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJiDloJCm_WPkhnDRwIXdZAL1NkdvjcohiHg&s ',
            title: 'Neuromancer',
            author: 'William Gibson',
            type: 'Sci-Fi',
            description: 'A cyberpunk classic that introduced cyberspace and reshaped the vision of artificial intelligence and the digital world.',
            rating: '4.3',
        },
        {
            id: nanoid(),
            img: ' https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr0K3obDHZqgbj9pC3FVP7i1jRdd4bhEjaWQ&s',
            title: 'Becoming',
            author: 'Michelle Obama',
            type: 'Non-Fiction',
            description: 'The memoir of former First Lady Michelle Obama, detailing her journey from the South Side of Chicago to the White House.',
            rating: '4.8',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8wjrW0Vg2HrZtC54Zr1-sCid5a5875HUBzw&s ',
            title: 'The Road',
            author: 'Cormac McCarthy',
            type: 'Fiction',
            description: 'A harrowing story of a father and son navigating a post-apocalyptic world, focusing on survival and moral ambiguity.',
            rating: '4.4',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOVD7QLpVAWQH3NDAPCPqF8UyEyCOwoI5BWg&s ',
            title: 'The Left Hand of Darkness',
            author: 'Ursula K. Le Guin',
            type: 'Sci-Fi',
            description: 'An exploration of gender and identity set on a planet where inhabitants are ambisexual, challenging societal norms.',
            rating: '4.5',
        },
        {
            id: nanoid(),
            img: ' https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9hruh6SZ0pbVNm9OQ5POGStdnIFiZEH-DoQ&s',
            title: 'Homo Deus',
            author: 'Yuval Noah Harari',
            type: 'Non-Fiction',
            description: 'A visionary book that examines the future of humanity, artificial intelligence, and genetic engineering.',
            rating: '4.7',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2IQq3FeGtwk3Z8rQnjmENl_qF7d5FMDehJA&s ',
            title: 'Foundation',
            author: 'Isaac Asimov',
            type: 'Sci-Fi',
            description: 'A science fiction epic about the decline of a vast galactic empire and the efforts to preserve knowledge.',
            rating: '4.4',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRWfrQF_TWnRF4Jx1IvvY9UQ0-8EvAd3q0aw&s ',
            title: 'Atomic Habits',
            author: 'James Clear',
            type: 'Non-Fiction',
            description: 'A comprehensive guide on how small changes in habits can lead to big improvements in personal growth.',
            rating: '4.7',
        },
        {
            id: nanoid(),
            img: ' https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYsqQ4dwA7oVhqDkcNv8IBB5IodmY8NKZwXw&s',
            title: 'Snow Crash',
            author: 'Neal Stephenson',
            type: 'Sci-Fi',
            description: 'A fast-paced cyberpunk adventure that critiques corporate control and the power of information.',
            rating: '4.5',
        },
        {
            id: nanoid(),
            img: ' https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXOGMyM_NJ5Xnkc1Qe0LOm6ETaNRsOVZdKLg&s',
            title: 'Thinking, Fast and Slow',
            author: 'Daniel Kahneman',
            type: 'Non-Fiction',
            description: 'A deep dive into the cognitive processes behind decision making, exploring the dichotomy between intuitive and logical thinking.',
            rating: '4.6',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKTu6c6BGi3VWiyS_2MBDOKIg0jY7fsrZmFQ&s ',
            title: 'The Odyssey',
            author: 'Homer',
            type: 'Fiction',
            description: 'An ancient Greek epic about the adventures of Odysseus as he journeys home after the Trojan War.',
            rating: '4.7',
        },
        {
            id: nanoid(),
            img: 'https://m.media-amazon.com/images/I/91PmsgqIcOL._AC_UF1000,1000_QL80_.jpg',
            title: '1984',
            author: 'George Orwell',
            type: 'Fiction',
            description: 'A dystopian social science fiction novel.',
            rating: '4.8',
        },
        {
            id: nanoid(),
            img: 'https://m.media-amazon.com/images/I/51j7zrSt+VL._SL500_.jpg',
            title: 'Moby-dick',
            author: 'Herman Melville',
            type: 'Fiction',
            description: 'A novel about the voyage of the whaling ship Pequod.',
            rating: '4.3',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgRE2-jEyIv-u9cibSY1x1J3ul-13zQf5X-A&s',
            title: 'War and Peace',
            author: 'Leo Tolstoy',
            type: 'Historical Fiction',
            description: 'A novel about the experiences of a young aristocrat during the Napoleonic era.',
            rating: '4.7',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQywX079hDLEPyfS--UFLrSIXBXadztr6APcQ&s',
            title: 'Pride and Prejudice',
            author: 'Jane Austen',
            type: 'Romance',
            description: 'A romantic novel that charts the emotional development of the protagonist, Elizabeth Bennet.',
            rating: '4.6',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTY9Gp4VyNUvk7uHFxCm2ljCx4M3lx3oF1Pg&s',
            title: 'Sherlock Holmes: The Complete Novels and Stories',
            author: 'Arthur Conan Doyle',
            type: 'Mystery',
            description: 'A collection of stories featuring the famous detective Sherlock Holmes and his friend Dr. Watson solving mysteries.',
            rating: '4.7',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRleeajgGt7I8jBAMZAXFg9oDYGnKuFgosuQw&s',
            title: 'Fahrenheit 451',
            author: 'Ray Bradbury',
            type: 'Sci-Fi',
            description: 'In a dystopian future where books are banned, a fireman named Guy Montag begins to question his role in society.',
            rating: '4.5',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLagM0235eKqtRgTpTPPdsKoj3hnsqAN5MWg&s',
            title: 'Gone Girl',
            author: 'Gillian Flynn',
            type: 'Thriller',
            description: 'A gripping psychological thriller about a woman who goes missing on her fifth wedding anniversary and her husband becomes the prime suspect.',
            rating: '4.2',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRS8g2pRmFF6s5deMrmflNf_kpJB57mk2oTcg&s ',
            title: 'The Hitchhiker\'s Guide to the Galaxy',
            author: 'Douglas Adams',
            type: 'Sci-Fi',
            description: 'A comedic science fiction series about Arthur Dent\'s adventures through space after Earth is destroyed to make way for a hyperspace bypass.',
            rating: '4.4',
        },
        {
            id: nanoid(),
            img: 'https://repository-images.githubusercontent.com/208488353/d123b800-d708-11e9-9cea-c1574f78a289',
            title: 'Eloquent JavaScript, Third Edition',
            author: 'Marijn Haverbeke',
            type: 'Programming',
            description: 'JavaScript lies at the heart of almost every modern web application, from social apps to game frameworks.',
            rating: '4.5',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT02Sr65HjZwrkHMH2SthKDdWK8J2NTvNifQw&s',
            title: 'Practical Modern JavaScript',
            author: 'Nicolás Bevacqua',
            type: 'Programming',
            description: 'A practical look at ES6 features in JavaScript.',
            rating: '4.4',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ98EmnxnBw3wp5k6IK6U3minJ-FmRjbpQccg&s',
            title: 'Understanding ECMAScript 6',
            author: 'Nicholas C. Zakas',
            type: 'Programming',
            description: 'A complete guide to ECMAScript 6 in JavaScript.',
            rating: '4.6',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8ece1CdbcLruOug9mn5EjZ9E_Qd2BymtC_Q&s',
            title: 'Speaking JavaScript',
            author: 'Axel Rauschmayer',
            type: 'Programming',
            description: 'Guides readers into and through JavaScript with a hands-on approach.',
            rating: '4.3',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe3V5MsleMPS4ipTXkUhdp8ENH278IX__Z6A&s',
            title: 'Learning JavaScript Design Patterns',
            author: 'Addy Osmani',
            type: 'Programming',
            description: 'A guide to JavaScript design patterns for efficient, maintainable code.',
            rating: '4.5',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX4NhYqt_VvM1OkVJ3BzEKA7-SCfket0IBLA&s',
            title: 'You Don\'t Know JS Yet',
            author: 'Kyle Simpson',
            type: 'Programming',
            description: 'An updated version of the popular "You Don\'t Know JS" series, covering JavaScript fundamentals.',
            rating: '4.8',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7Zad5HmhpWJXv42gBIm8ppaWqOuXk3OTsGQ&s',
            title: 'Pro Git',
            author: 'Scott Chacon and Ben Straub',
            type: 'Programming',
            description: 'A comprehensive guide to using Git effectively.',
            rating: '4.7',
        },
        {
            id: nanoid(),
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSk-t74ua7J_sR-SCa1f217uFe6U_H94wE5Pw&s',
            title: 'Rethinking Productivity in Software Engineering',
            author: 'Caitlin Sadowski, Thomas Zimmermann',
            type: 'Software Engineering',
            description: 'Insights on software engineering productivity from leaders in the field.',
            rating: '4.6',
        }
]